# Generated by Django 3.2 on 2022-02-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaeaties2app', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_email',
            new_name='email',
        ),
    ]
